name: Generate
inputs:
  source_dir:
    description: Directory which contains the top CMakeLists.txt file.
    default: .
    required: true
  output_dir:
    description: Directory where CMake outputs generated rules.
    default: out-cmake
    required: true
runs:
  using: composite
  steps:
    - uses: papundekel/PPactions/run@v1
      with:
        command: cmake -S ${{ inputs.source_dir }} -B ${{ inputs.output_dir }} -G "Ninja Multi-Config"
