name: Download directory
inputs:
  name:
    description: Artifact name.
    required: true
  path:
    description: Directory path.
    default: .
    required: true
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.name }}
    - uses: Petkr/PPactions/run@v1
      with:
        command: tar -xf ${{ inputs.name }}.tar -C ${{ inputs.path }}; rm ${{ inputs.name }}.tar
