name: CPack
inputs:
  config_dir:
    description: Directory in which the CPackConfig.cmake is located.
    default: out-cmake
    required: true
  output_dir:
    description: Directory where CPack outputs packages.
    default: out-cpack
    required: true
  config:
    description: Configuration to package.
    default: Release
    required: true
runs:
  using: composite
  steps:
    - uses: papundekel/PPactions/run@v1
      with:
        command: cpack --config ${{ inputs.config_dir }}/CPackConfig.cmake -B ${{ inputs.output_dir }} -C ${{ inputs.config }} -D CPACK_INCLUDE_TOPLEVEL_DIRECTORY=0
