name: Upload directory
inputs:
  name:
    description: Artifact name.
    required: true
  path:
    description: Directory path.
    required: true
runs:
  using: composite
  steps:
    - uses: papundekel/PPactions/run@v1
      with:
        command: mkdir ${{ inputs.path }} 2> /dev/null || true; tar -cf ${{ inputs.name }}.tar ${{ inputs.path }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}.tar
    - uses: papundekel/PPactions/run@v1
      with:
        command: rm ${{ inputs.name }}.tar
